### ISSUE TITLE
Missing `Diagnosis` entry point & operations

### ISSUE THREAD

**Issue by foreseaz** [nleak/nleak#3]

**Comment by yizhou0522** [comment]
I will take this

**Comment by foreseaz** [comment]
> I will take this

Please assign yourself on the right hand side `Assignees`

**Comment by foreseaz** [comment]
If you're not familiar with the issue, please schedule a meeting with me via Google Meet. @yizhou0522

**Comment by foreseaz** [comment]
@yizhou0522 any updates?

**Comment by yizhou0522** [comment]
Tasks Completed: Researched on all operations inside DiagnosisOperations and started to integrate them into NLeak; configure and setup the BLeak and currently generating memory leak results using BLeak; did studies on previous sample leak results on http://plasma-umass.org/BLeak/viewer/index.html#url=../mailpile_output.json; created new branch to specifically resolve this task; Still working on testing  ProgramRunOperation in Nodejs environment

TODO Tasks: Tested and see if these operations (ProgramRunOperation, InstrumentGrowingPathsOperation, StepSeriesOperation, GetGrowthStacksOperation) will work in NodeJS environment; recorded and presented the results in Google slides

![image](https://user-images.githubusercontent.com/47721874/195456688-bf747b82-5fea-4e10-9d8a-75f2dd3fc51a.png)
![image](https://user-images.githubusercontent.com/47721874/195456747-f084bc4b-4015-4fde-9d5d-251d02ebcac8.png)

**Comment by foreseaz** [comment]
@yizhou0522 do you think this issue could be closed for now?

**Comment by yizhou0522** [comment]
@foreseaz For the following task, I guess perhaps we can also use this issue to handle DiagnoseLeaks() function rewrite as previously discussed. If you think it's better to change the name of the issue to better represent what we've done, then we can close this and open a new one instead

**Comment by foreseaz** [comment]
I think we can create a new issue and close this one, since not much discussion has been posted here. Will link the new issue to this.
