### ISSUE TITLE
Problem: Missing implementation of `own_require` on agent and guest app JS files

### ISSUE THREAD

**Issue by foreseaz** [nleak/nleak#40]
- [x] implement the require function in wrapper
- [ ] ...

**Comment by Frost-Lee** [comment]
Working with @foreseaz on the branch `own_require`. The wrapper integrates the rewrite and reads command line arguments (such as the rewrite flag) now. However, `wrapper.js` is incompatible with some TypeScript modules we used. Currently working on resolving them.

**Comment by foreseaz** [comment]
This has been resolved by #46
