### ISSUE TITLE
Cache Problem before DiagnosisLeaks: Need research on the three possible solutions

### ISSUE THREAD

**Issue by foreseaz** [nleak/nleak#43]
Cache issue:
- [ ] require cache control?
- [x] restarting the child process
- [ ] or live edit (time: 1hr and no more.) https://developer.chrome.com/en/blog/new-in-devtools-105/#live-edit

**Comment by foreseaz** [comment]
https://github.com/plasma-umass/BLeak/blob/60836b01a8be42242f079e53639065feaba74e75/src/lib/stack_frame_converter.ts#L38

**Comment by mdblr** [comment]
For reference: https://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate

**Comment by mdblr** [comment]
The function `process.dlopen(module, filename[, flags])`[(link)](https://nodejs.org/api/process.html#processdlopenmodule-filename-flags) may also help you!

**Comment by Frost-Lee** [comment]
Currently we chose to restart the child process for the guest application when switching rewrite mode. This is consistent with Bleak where the rewriting is configured by an interceptor and `ProgramRunOperation` triggers `navigateToURL`, which reloads the corresponding webpage.  See https://github.com/nleak/nleak/blob/8a2ebaeca529262c6aaf7795da96f5caf79c953f/core/node_driver.ts#L184-L191 for the implementation.

**Comment by foreseaz** [comment]
@Frost-Lee great!
