### ISSUE TITLE
Missing `ConfigureProxyOperation` for NodeJS environment 

### ISSUE THREAD

**Issue by foreseaz** [nleak/nleak#5]
Without `proxy`, then how to implement `ConfigureProxyOperation`?

**Comment by foreseaz** [comment]
@Frost-Lee it's related to `agent` part, you can also include this issue in your scope.

**Comment by Frost-Lee** [comment]
We are planning on integrating the rewriting feature (#8 ) by overriding `require` in JavaScript.

**Comment by Frost-Lee** [comment]
`ConfigureProxyOperation` is replaced by `ConfigureRewriteOperation`, see https://github.com/nleak/nleak/commit/8a2ebaeca529262c6aaf7795da96f5caf79c953f.
